### ISSUE TITLE
file name for output pickle file

### ISSUE THREAD

**Issue by skdebray** [ml4ai/dass-wills#1]
@pawnsac Thanks for the code.   I have a couple of minor tweaks I'd like to request:

1. Right now the name of the output pickle file is derived from that of the input JSON file.  This potentially has the disadvantage that for an input JSON file `will01.json` the piclke file is named `will01.json.pickle`, which can be confusing by making it seem as though it's the JSON file that's being pickled.  Would it be possible to name the output pickle file by removing the `.json` suffix from the input JSON file, i.e., if the JSON file is `will01.json` then the output pickle file is `will01.pickle`.
2. In the output line printed by the program, `exporting the will object...` can you just add the name of the file being exported to?

**Comment by muazali64** [comment]
Addressed both of them in the commit @feb02cb.
