### ISSUE TITLE
devolve_will.py 

### ISSUE THREAD

**Issue by skdebray** [ml4ai/dass-wills#2]
@pawnsac The file `devolve_will.py` has a few style issues that should be fixed.  Where possible let's try to be consistent with PEP-8 (https://peps.python.org/pep-0008/).

- Maximum line length = 79 (https://peps.python.org/pep-0008/#maximum-line-length)
- Adjacent function definitions should be separated by two blank lines (https://peps.python.org/pep-0008/#blank-lines)
- The file has a banner "UTILITIES" near the top but no other banners, suggesting that the file consists entirely of utilities and nothing else.
- Please check the `import` statements at the top to make sure they make sense.  For example, `Person` is imported but it's not used in the code.

**Comment by muazali64** [comment]
Addressed the concerns.

**Comment by skdebray** [comment]
@pawnsac There still seem to be several long lines that are over the 79-char length.  Is it possible to fix these?

**Comment by adarshp** [comment]
@skdebray @pawnsac  - you might find this tool useful for automatically formatting and linting your Python code: https://github.com/astral-sh/ruff

**Comment by skdebray** [comment]
@adarshp Thanks for that pointer, that's very helpful!

On an unrelated note, are you still at UA?

--s

**Comment by adarshp** [comment]
No problem @skdebray ! And yes, I'm still here :)

Currently I'm research faculty in the iSchool, and will start as a tenure-track assistant professor in the iSchool this fall.

**Comment by skdebray** [comment]
@adarshp Congratulations on your new position!  That's exciting, and well-deserved. 

If you're around this summer, let's catch up one of these days.  I'm travelling all of next week, but will be around after that.

**Comment by adarshp** [comment]
Thanks @skdebray ! I am around and yes, definitely, let's catch up. I'll email you to set up a time :)

**Comment by muazali64** [comment]
> @pawnsac There still seem to be several long lines that are over the 79-char length. Is it possible to fix these?

I have addressed it. Let me know if anything else needs to be addressed.
